version: "3"
services:

  schoolio_frontend:
    build:
      context: ./panel
      dockerfile: Dockerfile
    depends_on:
      - schoolio_backend
    container_name: schoolio_frontend
    ports:
      - "3100:3000"
    networks:
      - project-network
  schoolio_backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - schoolio_db
    ports:
      - "8100:8000"
    container_name: schoolio_backend
    volumes:
      - ./api/media:/opt/pdd/media
    networks:
      - project-network

  schoolio_telebot:
    build:
      context: './bot'
      dockerfile: Dockerfile
    depends_on:
      - schoolio_backend
    container_name: schoolio_telebot
    networks:
      - project-network

  schoolio_db:
    image: postgres:latest
    container_name: schoolio_db
    environment:
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: Lp2nZxYOCcPhzrXj
      POSTGRES_DB: school
    ports:
      - "5410:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

networks:
  project-network:

volumes:
  postgres_data:
  schoolio_data:
