"""create models

Revision ID: e92eba811580
Revises: 
Create Date: 2023-08-28 09:26:59.178874

"""
import ormar
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92eba811580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('slug', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('lesson_blocks',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('slug', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('users',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('last_jwt_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('otp_secret', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('courses_lessonblocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lessonblock', sa.BigInteger(), nullable=True),
    sa.Column('course', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.idx'], name='fk_courses_lessonblocks_courses_course_idx', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lessonblock'], ['lesson_blocks.idx'], name='fk_courses_lessonblocks_lesson_blocks_lessonblock_idx', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_courses',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('slug', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('course', sa.BigInteger(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.idx'], name='fk_user_courses_courses_idx_course'),
    sa.ForeignKeyConstraint(['user'], ['users.idx'], name='fk_user_courses_users_idx_user'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_courses')
    op.drop_table('courses_lessonblocks')
    op.drop_table('users')
    op.drop_table('lesson_blocks')
    op.drop_table('courses')
    # ### end Alembic commands ###
